
variable "new_ssh_pass" {
  type    = string
  default = "Volterra123"
}

variable "old_ssh_pass" {
  type    = string
  default = "Volterra123"
}

source "qemu" "autogenerated_1" {
  boot_command = ["<wait5><enter><wait480>", "admin<enter><wait3>", "${var.old_ssh_pass}<enter><wait3>", "${var.old_ssh_pass}<enter><wait3>", "${var.new_ssh_pass}<enter><wait3>", "${var.new_ssh_pass}<enter><wait3>"]
  boot_wait    = "2s"
  cpus         = 4
  format       = "qcow2"
  headless     = true
  #http_directory   = "http"
  #iso_checksum     = "0d6c8473a526d6c289bab8b899ed1244"
  iso_checksum = "381da8b538456669144a6ff5eaf9ea41"
  #iso_target_path  = "/var/lib/libvirt/images/iso/"
  #iso_urls         = ["/var/lib/libvirt/images/iso/vsb-ves-ce-certifiedhw-generic-production-centos-7.2009.27-202211040823.1667791030.iso"]
  iso_url          = "/var/lib/libvirt/images/xc-template"
  disk_image       = true
  memory           = "16384"
  skip_compaction  = true
  output_directory = "output-xc"
  qemuargs = [
    ["-cpu", "host"],
    ["-device", "isa-fdc,id=floppy-bus"],
    # ["-blockdev", "{\"driver\":\"file\",\"filename\":\"/var/lib/libvirt/images/xc-cloudinit.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}"],
    # ["-blockdev", "{\"node-name\":\"libvirt-1-format\",\"read-only\":true,\"driver\":\"raw\",\"file\":\"libvirt-1-storage\"}"],
    # ["-device", "ide-cd,bus=ide.0,drive=libvirt-1-format,id=sata0-0-0"]
    ["-drive", "file=/var/lib/libvirt/images/xc-cloudinit.iso,if=none,media=cdrom,id=drive-sata0-0-4,readonly=on,format=raw"],
    ["-device", "ide-cd,bus=ide.4,drive=drive-sata0-0-4,id=sata0-0-4"]
  ]
  ssh_password = var.new_ssh_pass
  #communicator     = "none"
  shutdown_timeout = "10m"
  ssh_timeout      = "9m"
  ssh_username     = "admin"
  machine_type     = "q35"
  shutdown_command = ""
  vm_name          = "xc.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

}
